[package]
name = "bytecheck_test"
version = "0.1.1"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Test suite for bytecheck crates"
license = "MIT"
repository = "https://github.com/djkoloski/bytecheck"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
bytecheck = { version = "0.0.0", path = "../bytecheck" }

[features]
default = ["std"]
const_generics = []
silent = []
std = []

