[package]
name = "bytecheck"
version = "0.4.1"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Derive macro for bytecheck"
license = "MIT"
documentation = "https://docs.rs/bytecheck"
repository = "https://github.com/djkoloski/bytecheck"
keywords = ["bytecheck", "validation", "zero-copy", "rkyv"]
categories = ["encoding"]
readme = "crates-io.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecheck_derive = { version = "=0.4.1", path = "../bytecheck_derive" }
memoffset = "0.6"
ptr_meta = "0.1"

[features]
default = []
const_generics = []